/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProviderIndexImport } from './routes/$provider/index'
import { Route as ProviderOwnerRepoPullPrIdImport } from './routes/$provider/$owner/$repo/pull/$prId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProviderIndexRoute = ProviderIndexImport.update({
  id: '/$provider/',
  path: '/$provider/',
  getParentRoute: () => rootRoute,
} as any)

const ProviderOwnerRepoPullPrIdRoute = ProviderOwnerRepoPullPrIdImport.update({
  id: '/$provider/$owner/$repo/pull/$prId',
  path: '/$provider/$owner/$repo/pull/$prId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$provider/': {
      id: '/$provider/'
      path: '/$provider'
      fullPath: '/$provider'
      preLoaderRoute: typeof ProviderIndexImport
      parentRoute: typeof rootRoute
    }
    '/$provider/$owner/$repo/pull/$prId': {
      id: '/$provider/$owner/$repo/pull/$prId'
      path: '/$provider/$owner/$repo/pull/$prId'
      fullPath: '/$provider/$owner/$repo/pull/$prId'
      preLoaderRoute: typeof ProviderOwnerRepoPullPrIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$provider': typeof ProviderIndexRoute
  '/$provider/$owner/$repo/pull/$prId': typeof ProviderOwnerRepoPullPrIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$provider': typeof ProviderIndexRoute
  '/$provider/$owner/$repo/pull/$prId': typeof ProviderOwnerRepoPullPrIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$provider/': typeof ProviderIndexRoute
  '/$provider/$owner/$repo/pull/$prId': typeof ProviderOwnerRepoPullPrIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$provider' | '/$provider/$owner/$repo/pull/$prId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$provider' | '/$provider/$owner/$repo/pull/$prId'
  id: '__root__' | '/' | '/$provider/' | '/$provider/$owner/$repo/pull/$prId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
  ProviderOwnerRepoPullPrIdRoute: typeof ProviderOwnerRepoPullPrIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProviderIndexRoute: ProviderIndexRoute,
  ProviderOwnerRepoPullPrIdRoute: ProviderOwnerRepoPullPrIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$provider/",
        "/$provider/$owner/$repo/pull/$prId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$provider/": {
      "filePath": "$provider/index.tsx"
    },
    "/$provider/$owner/$repo/pull/$prId": {
      "filePath": "$provider/$owner/$repo/pull/$prId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
